import platform

from qtCore import *
from ui.components.base.baseLine import BaseVLine, BaseHLine
from ui.components.base.basePushButton import BasePushButton
from ui.components.settingsSwitch import SwitchButton


class PrintingPage(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)

        self.layout = QVBoxLayout(self)
        self.layout.setContentsMargins(0, 0, 0, 0)
        self.layout.setSpacing(10)

        self.frame = QFrame(self)
        self.frame_layout = QVBoxLayout(self.frame)
        self.frame_layout.setContentsMargins(20, 0, 20, 20)
        self.frame_layout.setSpacing(10)

        self.file_frame = QFrame(self)
        self.file_frame.setObjectName("frameBox")
        self.file_frame_layout = QVBoxLayout(self.file_frame)
        self.file_frame_layout.setContentsMargins(0, 0, 0, 0)
        self.file_frame_layout.setSpacing(0)
        self.file_image = QLabel(self.file_frame)
        self.file_image.setAlignment(Qt.AlignCenter)
        self.file_image.setPixmap(QPixmap("resource/image/hyper-x").scaledToWidth(360))
        if is_release:
            self.file_image.setFixedSize(360, 360)
        self.file_image.setAlignment(Qt.AlignCenter)
        self.file_frame_layout.addWidget(self.file_image)
        self.file_frame_layout.addWidget(BaseHLine())
        self.file_frame_bottom_layout = QHBoxLayout()
        self.file_frame_bottom_layout.setContentsMargins(16, 0, 4, 0)
        self.file_frame_bottom_layout.setSpacing(4)
        self.file_name = QLabel()
        self.file_name.setFixedSize(226, 64)
        self.file_name.adjustSize()
        self.file_name.setWordWrap(True)
        self.file_frame_bottom_layout.addWidget(self.file_name)
        self.file_frame_bottom_line_1 = BaseVLine()
        self.file_frame_bottom_line_1.setFixedHeight(64)
        self.file_frame_bottom_layout.addWidget(self.file_frame_bottom_line_1)
        self.pause_print_button = BasePushButton()
        self.pause_print_button.setObjectName("pausePrintButton")
        self.pause_print_button.setFixedSize(48, 48)
        self.file_frame_bottom_layout.addWidget(self.pause_print_button)
        self.file_frame_bottom_line_2 = BaseVLine()
        self.file_frame_bottom_line_2.setFixedHeight(36)
        self.file_frame_bottom_layout.addWidget(self.file_frame_bottom_line_2)
        self.stop_print_button = BasePushButton()
        self.stop_print_button.setObjectName("stopPrintButton")
        self.stop_print_button.setFixedSize(48, 48)
        self.file_frame_bottom_layout.addWidget(self.stop_print_button)
        self.file_frame_layout.addLayout(self.file_frame_bottom_layout)
        self.frame_layout.addWidget(self.file_frame)

        self.progress_frame = QFrame()
        self.progress_frame.setObjectName("frameBox")
        self.progress_frame.setFixedHeight(100)
        self.progress_frame_layout = QVBoxLayout(self.progress_frame)
        self.progress_frame_layout.setContentsMargins(20, 10, 20, 10)
        self.progress_frame_layout.setSpacing(10)
        self.progress_frame_label_layout = QHBoxLayout()
        self.progress_frame_label_layout.setContentsMargins(0, 0, 0, 0)
        self.progress_frame_label_layout.setSpacing(0)
        self.print_time = QLabel()
        self.print_time.setObjectName("printTime")
        self.print_time.setStyleSheet("font-size: 28px")
        self.print_time.setAlignment(Qt.AlignLeft | Qt.AlignBottom)
        self.progress_frame_label_layout.addWidget(self.print_time)
        self.print_progress_label = QLabel()
        self.print_progress_label.setObjectName("printProgressLabel")
        self.print_progress_label.setStyleSheet("font-weight: 500; font-size: 40px")
        self.print_progress_label.setAlignment(Qt.AlignRight | Qt.AlignBottom)
        self.progress_frame_label_layout.addWidget(self.print_progress_label)
        self.progress_frame_layout.addLayout(self.progress_frame_label_layout)
        self.print_progress_bar = QProgressBar()
        self.print_progress_bar.setFixedHeight(10)
        self.print_progress_bar.setTextVisible(False)
        self.print_progress_bar.setMinimum(0)
        self.print_progress_bar.setMaximum(100)
        self.progress_frame_layout.addWidget(self.print_progress_bar)
        self.frame_layout.addWidget(self.progress_frame)

        self.thermal_frame = QFrame()
        self.thermal_frame.setObjectName("frameBox")
        self.thermal_frame.setFixedHeight(120)
        self.thermal_frame_layout = QGridLayout(self.thermal_frame)
        self.thermal_frame_layout.setContentsMargins(10, 10, 10, 10)
        self.thermal_frame_layout.setSpacing(0)
        self.thermal_left_logo = QLabel()
        self.thermal_left_logo.setObjectName("leftLogo")
        self.thermal_frame_layout.addWidget(self.thermal_left_logo, 0, 0, 1, 1)
        self.thermal_left_button = BasePushButton()
        self.thermal_left_button.setObjectName("smallButton")
        self.thermal_left_button.setFixedHeight(40)
        self.thermal_frame_layout.addWidget(self.thermal_left_button, 0, 1, 1, 3)
        self.thermal_right_logo = QLabel()
        self.thermal_right_logo.setObjectName("rightLogo")
        self.thermal_frame_layout.addWidget(self.thermal_right_logo, 0, 4, 1, 1)
        self.thermal_right_button = BasePushButton()
        self.thermal_right_button.setObjectName("smallButton")
        self.thermal_right_button.setFixedHeight(40)
        self.thermal_frame_layout.addWidget(self.thermal_right_button, 0, 5, 1, 3)
        self.thermal_bed_logo = QLabel()
        self.thermal_bed_logo.setObjectName("bedLogo")
        self.thermal_frame_layout.addWidget(self.thermal_bed_logo, 1, 0, 1, 1)
        self.thermal_bed_button = BasePushButton()
        self.thermal_bed_button.setObjectName("smallButton")
        self.thermal_bed_button.setFixedHeight(40)
        self.thermal_frame_layout.addWidget(self.thermal_bed_button, 1, 1, 1, 3)
        self.thermal_chamber_logo = QLabel()
        self.thermal_chamber_logo.setObjectName("chamberLogo")
        self.thermal_frame_layout.addWidget(self.thermal_chamber_logo, 1, 4, 1, 1)
        self.thermal_chamber_button = BasePushButton()
        self.thermal_chamber_button.setObjectName("smallButton")
        self.thermal_chamber_button.setFixedHeight(40)
        self.thermal_frame_layout.addWidget(self.thermal_chamber_button, 1, 5, 1, 3)
        self.frame_layout.addWidget(self.thermal_frame)

        self.motor_frame = QFrame()
        self.motor_frame.setFixedHeight(80)
        self.motor_layout = QHBoxLayout(self.motor_frame)
        self.motor_layout.setContentsMargins(0, 0, 0, 0)
        self.motor_layout.setSpacing(10)

        self.motor_z_frame = QFrame()
        self.motor_z_frame.setObjectName("frameBox")
        self.motor_z_frame.setFixedHeight(80)
        self.motor_z_layout = QHBoxLayout(self.motor_z_frame)
        self.motor_z_layout.setContentsMargins(10, 10, 10, 10)
        self.motor_z_layout.setSpacing(0)
        self.motor_z_logo = QLabel()
        self.motor_z_logo.setObjectName("zLogo")
        self.motor_z_layout.addWidget(self.motor_z_logo, 1)
        self.motor_z = QLabel()
        self.motor_z.setAlignment(Qt.AlignCenter)
        self.motor_z_layout.addWidget(self.motor_z, 3)
        self.motor_layout.addWidget(self.motor_z_frame, 1)

        self.baby_step_frame = QFrame()
        self.baby_step_frame.setObjectName("frameBox")
        self.baby_step_frame.setFixedHeight(80)
        self.baby_step_layout = QHBoxLayout(self.baby_step_frame)
        self.baby_step_layout.setContentsMargins(0, 0, 0, 0)
        self.baby_step_layout.setSpacing(0)
        self.baby_step_button = BasePushButton()
        self.baby_step_button.setObjectName("smallButton")
        self.baby_step_layout.addWidget(self.baby_step_button)
        self.motor_layout.addWidget(self.baby_step_frame, 1)
        self.frame_layout.addWidget(self.motor_frame)

        self.fan_frame = QFrame()
        self.fan_frame.setFixedHeight(160)
        self.fan_frame_layout = QHBoxLayout(self.fan_frame)
        self.fan_frame_layout.setContentsMargins(0, 0, 0, 0)
        self.fan_frame_layout.setSpacing(10)

        self.fan_left_frame = QFrame()
        self.fan_left_frame.setObjectName("frameBox")
        self.fan_left_frame_layout = QGridLayout(self.fan_left_frame)
        self.fan_left_frame_layout.setContentsMargins(10, 10, 10, 10)
        self.fan_left_frame_layout.setSpacing(0)
        self.fan_cool_left_logo = QLabel()
        self.fan_cool_left_logo.setObjectName("fanLeftLogo")
        self.fan_left_frame_layout.addWidget(self.fan_cool_left_logo, 0, 0, 1, 1)
        self.fan_cool_left = QLabel()
        self.fan_cool_left.setAlignment(Qt.AlignCenter)
        self.fan_left_frame_layout.addWidget(self.fan_cool_left, 0, 1, 1, 3)
        self.fan_cool_right_logo = QLabel()
        self.fan_cool_right_logo.setObjectName("fanRightLogo")
        self.fan_left_frame_layout.addWidget(self.fan_cool_right_logo, 1, 0, 1, 1)
        self.fan_cool_right = QLabel()
        self.fan_cool_right.setAlignment(Qt.AlignCenter)
        self.fan_left_frame_layout.addWidget(self.fan_cool_right, 1, 1, 1, 3)
        self.fan_chamber_logo = QLabel()
        self.fan_chamber_logo.setObjectName("fanChamberLogo")
        self.fan_left_frame_layout.addWidget(self.fan_chamber_logo, 2, 0, 1, 1)
        self.fan_chamber = QLabel()
        self.fan_chamber.setAlignment(Qt.AlignCenter)
        self.fan_left_frame_layout.addWidget(self.fan_chamber, 2, 1, 1, 3)
        self.fan_frame_layout.addWidget(self.fan_left_frame)

        self.fan_right_frame = QFrame()
        self.fan_right_frame.setObjectName("frameBox")
        self.fan_right_frame_layout = QGridLayout(self.fan_right_frame)
        self.fan_right_frame_layout.setContentsMargins(10, 10, 10, 10)
        self.fan_right_frame_layout.setSpacing(0)
        self.fan_left_logo = QLabel()
        self.fan_left_logo.setObjectName("fanModelLeftLogo")
        self.fan_right_frame_layout.addWidget(self.fan_left_logo, 0, 0, 1, 1)
        self.fan_left_button = BasePushButton()
        self.fan_left_button.setObjectName("smallButton")
        self.fan_left_button.setFixedHeight(40)
        self.fan_right_frame_layout.addWidget(self.fan_left_button, 0, 1, 1, 3)
        self.fan_right_logo = QLabel()
        self.fan_right_logo.setObjectName("fanModelRightLogo")
        self.fan_right_frame_layout.addWidget(self.fan_right_logo, 1, 0, 1, 1)
        self.fan_right_button = BasePushButton()
        self.fan_right_button.setObjectName("smallButton")
        self.fan_right_button.setFixedHeight(40)
        self.fan_right_frame_layout.addWidget(self.fan_right_button, 1, 1, 1, 3)
        self.fan_exhaust_logo = QLabel()
        self.fan_exhaust_logo.setObjectName("fanExhaustLogo")
        self.fan_right_frame_layout.addWidget(self.fan_exhaust_logo, 2, 0, 1, 1)
        self.fan_exhaust_button = BasePushButton()
        self.fan_exhaust_button.setObjectName("smallButton")
        self.fan_exhaust_button.setFixedHeight(40)
        self.fan_right_frame_layout.addWidget(self.fan_exhaust_button, 2, 1, 1, 3)
        self.fan_frame_layout.addWidget(self.fan_right_frame)
        self.frame_layout.addWidget(self.fan_frame)

        self.speed_frame = QFrame()
        self.speed_frame.setFixedHeight(80)
        self.speed_frame_layout = QHBoxLayout(self.speed_frame)
        self.speed_frame_layout.setContentsMargins(0, 0, 0, 0)
        self.speed_frame_layout.setSpacing(10)

        self.speed_print_frame = QFrame()
        self.speed_print_frame.setObjectName("frameBox")
        self.speed_print_frame_layout = QHBoxLayout(self.speed_print_frame)
        self.speed_print_frame_layout.setContentsMargins(10, 10, 10, 10)
        self.speed_print_frame_layout.setSpacing(0)
        self.speed_print_logo = QLabel()
        self.speed_print_logo.setObjectName("speedLogo")
        self.speed_print_frame_layout.addWidget(self.speed_print_logo, 1)
        self.speed_print_button = BasePushButton()
        self.speed_print_button.setObjectName("smallButton")
        self.speed_print_button.setFixedHeight(40)
        self.speed_print_frame_layout.addWidget(self.speed_print_button, 3)
        self.speed_frame_layout.addWidget(self.speed_print_frame, 1)

        self.speed_flow_frame = QFrame()
        self.speed_flow_frame.setObjectName("frameBox")
        self.speed_flow_frame_layout = QHBoxLayout(self.speed_flow_frame)
        self.speed_flow_frame_layout.setContentsMargins(10, 10, 10, 10)
        self.speed_flow_frame_layout.setSpacing(0)
        self.speed_flow_logo = QLabel()
        self.speed_flow_logo.setObjectName("flowLogo")
        self.speed_flow_frame_layout.addWidget(self.speed_flow_logo, 1)
        self.speed_flow_button = BasePushButton()
        self.speed_flow_button.setObjectName("smallButton")
        self.speed_flow_button.setFixedHeight(40)
        self.speed_flow_frame_layout.addWidget(self.speed_flow_button, 3)
        self.speed_frame_layout.addWidget(self.speed_flow_frame, 1)
        self.frame_layout.addWidget(self.speed_frame)

        self.filament_frame = QFrame()
        self.filament_frame.setFixedHeight(80)
        self.filament_frame_layout = QHBoxLayout(self.filament_frame)
        self.filament_frame_layout.setContentsMargins(0, 0, 0, 0)
        self.filament_frame_layout.setSpacing(10)

        self.filament_detector_frame = QFrame()
        self.filament_detector_frame.setObjectName("frameBox")
        self.filament_detector_frame_layout = QHBoxLayout(self.filament_detector_frame)
        self.filament_detector_frame_layout.setContentsMargins(10, 10, 10, 10)
        self.filament_detector_frame_layout.setSpacing(0)
        self.filament_detector_text = QLabel()
        self.filament_detector_text.setAlignment(Qt.AlignCenter)
        self.filament_detector_frame_layout.addWidget(self.filament_detector_text)
        self.filament_detector_enabled = SwitchButton()
        self.filament_detector_frame_layout.addWidget(self.filament_detector_enabled)
        self.filament_frame_layout.addWidget(self.filament_detector_frame, 1)

        self.filament_changed_frame = QFrame()
        self.filament_changed_frame.setObjectName("frameBox")
        self.filament_changed_layout = QHBoxLayout(self.filament_changed_frame)
        self.filament_changed_layout.setContentsMargins(0, 0, 0, 0)
        self.filament_changed_layout.setSpacing(0)
        self.filament_changed_button = BasePushButton()
        self.filament_changed_button.setObjectName("smallButton")
        self.filament_changed_layout.addWidget(self.filament_changed_button)
        self.filament_frame_layout.addWidget(self.filament_changed_frame, 1)
        self.frame_layout.addWidget(self.filament_frame)
        self.layout.addWidget(self.frame)

        self.file_name.setText("print.gcode")

    def showEvent(self, a0: QShowEvent) -> None:
        self.re_translate_ui()

    def re_translate_ui(self):
        self.thermal_left_button.setText("-")
        self.thermal_right_button.setText("-")
        self.thermal_bed_button.setText("-")
        self.thermal_chamber_button.setText("-")
        self.motor_z.setText("-")
        self.fan_cool_left.setText("-")
        self.fan_cool_right.setText("-")
        self.fan_chamber.setText("-")
        self.fan_left_button.setText("-")
        self.fan_right_button.setText("-")
        self.fan_exhaust_button.setText("-")
        self.speed_print_button.setText("-")
        self.speed_flow_button.setText("-")
        self.baby_step_button.setText(self.tr("Baby Step"))
        self.filament_changed_button.setText(self.tr("Replace Filament"))
        self.filament_detector_text.setText(self.tr("Filament\nDetection"))

    def set_file_name(self, file):
        self.file_name.setText(file)
