import platform

from qtCore import *
from ui.base.baseLine import BaseVLine, BaseHLine


class PrintingPage(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.frame = QFrame(self)

        self.file_frame = QFrame(self)
        self.file_image = QLabel(self.file_frame)
        self.file_image.setAlignment(Qt.AlignCenter)
        self.file_image.setPixmap(QPixmap("resource/image/hyper-x").scaledToWidth(360))
        self.file_name = QLabel()
        # self.pause_print_button = QPushButton()
        self.stop_print_button = QPushButton()

        self.progress_frame = QFrame()
        self.print_time = QLabel()
        self.print_progress_label = QLabel()
        self.print_progress_bar = QProgressBar()

        self.thermal_frame = QFrame()
        self.thermal_left = QLabel()
        self.thermal_right = QLabel()
        self.thermal_bed = QLabel()
        self.thermal_chamber = QLabel()
        self.thermal_left_button = QPushButton()
        self.thermal_right_button = QPushButton()
        self.thermal_bed_button = QPushButton()
        self.thermal_chamber_button = QPushButton()

        self.fan_frame = QFrame()
        self.fan_cool_left = QLabel()
        self.fan_cool_right = QLabel()
        self.fan_chamber = QLabel()
        self.fan_left = QLabel()
        self.fan_right = QLabel()
        self.fan_exhaust = QLabel()
        self.fan_cool_left_button = QPushButton()
        self.fan_cool_right_button = QPushButton()
        self.fan_chamber_button = QPushButton()
        self.fan_left_button = QPushButton()
        self.fan_right_button = QPushButton()
        self.fan_exhaust_button = QPushButton()

        self.motor_frame = QFrame()
        self.motor_x = QLabel()
        self.motor_y = QLabel()
        self.motor_z = QLabel()
        self.motor_e = QLabel()
        self.motor_x_button = QPushButton()
        self.motor_y_button = QPushButton()
        self.motor_z_button = QPushButton()
        self.motor_e_button = QPushButton()

        self.speed_frame = QFrame()
        self.speed_print = QLabel()
        self.speed_flow = QLabel()
        self.speed_print_button = QPushButton()
        self.speed_flow_button = QPushButton()

        self.stop_print_button.setFixedSize(96, 48)
        self.speed_print_button.setFixedHeight(40)
        self.speed_flow_button.setFixedHeight(40)
        self.motor_x_button.setFixedHeight(40)
        self.motor_y_button.setFixedHeight(40)
        self.motor_z_button.setFixedHeight(40)
        self.motor_e_button.setFixedHeight(40)
        self.fan_cool_left_button.setFixedHeight(40)
        self.fan_cool_right_button.setFixedHeight(40)
        self.fan_chamber_button.setFixedHeight(40)
        self.fan_left_button.setFixedHeight(40)
        self.fan_right_button.setFixedHeight(40)
        self.fan_exhaust_button.setFixedHeight(40)
        self.thermal_left_button.setFixedHeight(40)
        self.thermal_right_button.setFixedHeight(40)
        self.thermal_bed_button.setFixedHeight(40)
        self.thermal_chamber_button.setFixedHeight(40)
        self.print_time.setStyleSheet("font-size: 28px")
        self.print_time.setAlignment(Qt.AlignLeft | Qt.AlignBottom)
        self.print_progress_label.setAlignment(Qt.AlignRight | Qt.AlignBottom)
        self.print_progress_label.setStyleSheet("font-weight: 500; font-size: 40px")
        self.print_progress_bar.setFixedHeight(10)
        self.print_progress_bar.setTextVisible(False)
        self.print_progress_bar.setMinimum(0)
        self.print_progress_bar.setMaximum(100)

        # self.button = QPushButton(self.file_frame)
        # self.button.setText("Image")

        self.initForm()
        self.initLayout()

    def initForm(self):
        if platform.system().lower() == 'linux':
            self.file_image.setFixedSize(360, 360)
        self.file_image.setAlignment(Qt.AlignCenter)
        self.file_frame.setObjectName("frameBox")
        self.progress_frame.setObjectName("frameBox")
        self.progress_frame.setFixedHeight(120)
        self.thermal_frame.setObjectName("frameBox")
        self.thermal_frame.setFixedHeight(120)
        self.fan_frame.setObjectName("frameBox")
        self.fan_frame.setFixedHeight(160)
        self.motor_frame.setObjectName("frameBox")
        self.motor_frame.setFixedHeight(120)
        self.speed_frame.setObjectName("frameBox")
        self.speed_frame.setFixedHeight(80)
        self.file_name.setFixedSize(234, 64)
        self.file_name.adjustSize()
        self.file_name.setWordWrap(True)

        self.thermal_left.setObjectName("leftLogo")
        self.thermal_right.setObjectName("rightLogo")
        self.thermal_bed.setObjectName("bedLogo")
        self.thermal_chamber.setObjectName("chamberLogo")

        self.fan_cool_left.setObjectName("fanLeftLogo")
        self.fan_cool_right.setObjectName("fanRightLogo")
        self.fan_chamber.setObjectName("fanChamberLogo")
        self.fan_left.setObjectName("fanLeftLogo")
        self.fan_right.setObjectName("fanRightLogo")
        self.fan_exhaust.setObjectName("fanExhaustLogo")

        self.motor_x.setObjectName("xLogo")
        self.motor_y.setObjectName("yLogo")
        self.motor_z.setObjectName("zLogo")
        self.motor_e.setObjectName("eLogo")

        self.speed_print.setObjectName("speedLogo")
        self.speed_flow.setObjectName("flowLogo")

        self.reTranslateUi()

    def initLayout(self):
        file_frame_bottom_line = BaseVLine()
        file_frame_bottom_line.setFixedHeight(48)
        file_frame_bottom_layout = QHBoxLayout()
        file_frame_bottom_layout.setContentsMargins(20, 0, 0, 0)
        file_frame_bottom_layout.addWidget(self.file_name)
        file_frame_bottom_layout.addWidget(file_frame_bottom_line)
        file_frame_bottom_layout.addWidget(self.stop_print_button)

        file_frame_line = BaseHLine()
        file_frame_layout = QVBoxLayout(self.file_frame)
        file_frame_layout.setContentsMargins(0, 0, 0, 0)
        file_frame_layout.setSpacing(0)
        file_frame_layout.addWidget(self.file_image)
        file_frame_layout.addWidget(file_frame_line)
        file_frame_layout.addLayout(file_frame_bottom_layout)

        speed_frame_layout = QHBoxLayout(self.speed_frame)
        speed_frame_layout.setContentsMargins(20, 20, 20, 20)
        speed_frame_layout.setSpacing(0)
        speed_frame_layout.addWidget(self.speed_print, 1)
        speed_frame_layout.addWidget(self.speed_print_button, 3)
        speed_frame_layout.addWidget(self.speed_flow, 1)
        speed_frame_layout.addWidget(self.speed_flow_button, 3)

        motor_layout = QGridLayout(self.motor_frame)
        motor_layout.setContentsMargins(20, 20, 20, 20)
        motor_layout.setSpacing(0)
        motor_layout.addWidget(self.motor_x, 0, 0, 1, 1)
        motor_layout.addWidget(self.motor_x_button, 0, 1, 1, 3)
        motor_layout.addWidget(self.motor_y, 0, 4, 1, 1)
        motor_layout.addWidget(self.motor_y_button, 0, 5, 1, 3)
        motor_layout.addWidget(self.motor_z, 1, 0, 1, 1)
        motor_layout.addWidget(self.motor_z_button, 1, 1, 1, 3)
        motor_layout.addWidget(self.motor_e, 1, 4, 1, 1)
        motor_layout.addWidget(self.motor_e_button, 1, 5, 1, 3)

        fan_frame_layout = QGridLayout(self.fan_frame)
        fan_frame_layout.setContentsMargins(20, 20, 20, 20)
        fan_frame_layout.setSpacing(0)
        fan_frame_layout.addWidget(self.fan_cool_left, 0, 0, 1, 1)
        fan_frame_layout.addWidget(self.fan_cool_left_button, 0, 1, 1, 3)
        fan_frame_layout.addWidget(self.fan_cool_right, 0, 4, 1, 1)
        fan_frame_layout.addWidget(self.fan_cool_right_button, 0, 5, 1, 3)
        fan_frame_layout.addWidget(self.fan_chamber, 1, 0, 1, 1)
        fan_frame_layout.addWidget(self.fan_chamber_button, 1, 1, 1, 3)
        fan_frame_layout.addWidget(self.fan_left, 1, 4, 1, 1)
        fan_frame_layout.addWidget(self.fan_left_button, 1, 5, 1, 3)
        fan_frame_layout.addWidget(self.fan_right, 2, 0, 1, 1)
        fan_frame_layout.addWidget(self.fan_right_button, 2, 1, 1, 3)
        fan_frame_layout.addWidget(self.fan_exhaust, 2, 4, 1, 1)
        fan_frame_layout.addWidget(self.fan_exhaust_button, 2, 5, 1, 3)

        thermal_frame_layout = QGridLayout(self.thermal_frame)
        thermal_frame_layout.setContentsMargins(20, 20, 20, 20)
        thermal_frame_layout.setSpacing(0)
        thermal_frame_layout.addWidget(self.thermal_left, 0, 0, 1, 1)
        thermal_frame_layout.addWidget(self.thermal_left_button, 0, 1, 1, 3)
        thermal_frame_layout.addWidget(self.thermal_right, 0, 4, 1, 1)
        thermal_frame_layout.addWidget(self.thermal_right_button, 0, 5, 1, 3)
        thermal_frame_layout.addWidget(self.thermal_bed, 1, 0, 1, 1)
        thermal_frame_layout.addWidget(self.thermal_bed_button, 1, 1, 1, 3)
        thermal_frame_layout.addWidget(self.thermal_chamber, 1, 4, 1, 1)
        thermal_frame_layout.addWidget(self.thermal_chamber_button, 1, 5, 1, 3)

        progress_frame_label_layout = QHBoxLayout()
        progress_frame_label_layout.setContentsMargins(0, 0, 0, 0)
        progress_frame_label_layout.setSpacing(0)
        progress_frame_label_layout.addWidget(self.print_time)
        progress_frame_label_layout.addWidget(self.print_progress_label)

        progress_frame_layout = QVBoxLayout(self.progress_frame)
        progress_frame_layout.setContentsMargins(20, 20, 20, 20)
        progress_frame_layout.setSpacing(10)
        progress_frame_layout.addLayout(progress_frame_label_layout)
        progress_frame_layout.addWidget(self.print_progress_bar)

        frame_layout = QVBoxLayout(self.frame)
        frame_layout.setContentsMargins(20, 0, 20, 20)
        frame_layout.setSpacing(10)
        frame_layout.addWidget(self.file_frame)
        frame_layout.addWidget(self.progress_frame)
        frame_layout.addWidget(self.thermal_frame)
        frame_layout.addWidget(self.motor_frame)
        frame_layout.addWidget(self.fan_frame)
        frame_layout.addWidget(self.speed_frame)

        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(10)
        layout.addWidget(self.frame)

    def set_file_name(self, file):
        self.file_name.setText(file)

    def reTranslateUi(self):
        self.file_name.setText("print.gcode")
        # self.pause_print_button.setText("Pause")
        self.stop_print_button.setText(self.tr("Stop"))
        self.thermal_left_button.setText("-")
        self.thermal_right_button.setText("-")
        self.thermal_bed_button.setText("-")
        self.thermal_chamber_button.setText("-")
        self.motor_x_button.setText("-")
        self.motor_y_button.setText("-")
        self.motor_z_button.setText("-")
        self.motor_e_button.setText("-")
        self.fan_cool_left_button.setText("-")
        self.fan_cool_right_button.setText("-")
        self.fan_chamber_button.setText("-")
        self.fan_left_button.setText("-")
        self.fan_right_button.setText("-")
        self.fan_exhaust_button.setText("-")
        self.speed_print_button.setText("-")
        self.speed_flow_button.setText("-")